name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # 授权生成 Provenance 证明
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm vitest run

      - name: Build package
        run: pnpm build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          echo "Build output verified:"
          ls -la dist/

      - name: Show package info
        run: |
          echo "Package name: $(node -p "require('./package.json').name")"
          echo "Package version: $(node -p "require('./package.json').version")"
          echo "Files to be published:"
          node -p "require('./package.json').files"

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 使用 GitHub Secrets 中的 Token
